#!/usr/bin/bash
# a scrip that installs nginx and configures a custom 404 page that
# contains a string using sed

sudo apt update -y
sudo apt upgrade -y
sudo apt -y install nginx
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

some_text='server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/'
sudo sed -i "s/server_name _;\$/${some_text}" /etc/nginx/sites-available/default
sudo sed -i "s/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart
