#!/usr/bin/env bash
# a bash script that installs HAproxy on a load balancer server to
# serve two web servers and distrubute requests using the default
# round robin algorithm

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt update # get updates
sudo apt-get -y install haproxy=2.0.\* # install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# backup the existing config file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# create configuration file for HAproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF

defaults
	mode http
	timeout client 10s
	timeout connect 50s
	timeout server 10s 
	timeout http-request 10s

backend backend_servers
	bind *:80
	mode http
	status enabled
	stats uri /haproxy?stats
	balance roundrobin
	option httpchk HEAD / HTTP/1.1\r\nHost: localhost

	server 297651-web-01 54.82.132.33:80 check
	server 297651-web-02 54.197.206.10:80 check
EOF

# enable HAproxy as a service
sudo systemctl enable haproxy

# Start HAproxy service
sudo systemctl start haproxy
