#!/usr/bin/env bash
# a bash script that creates an sql dump and creates an tar.gz
# archive from the sql dump
file_name="backup.sql"
current_date=$(date -u '+%d-%m-%Y')
sudo mysqldump -uroot -p "$1" --all-databases > $file_name
tar -czvf "$current_date.tar.gz" "$file_name"
