#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument
arg=$1
total_arg=$#

if [ "$total_arg" == 1 ]; then
	ping -c 5 "$arg"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
