#!/usr/bin/env bash
# bash script that starts nginx

sudo ufw allow 'Nginx HTTP'
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
