#!/usr/bin/env bash
# bash script that starts nginx
sudo apt-get -y update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/listen [::]:80 default_server;/c\    listen 80;' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
