#!/usr/bin/env bash
# a bash (init) script that manages a file with start, stop and restart cmd
file_name="my_process.pid"

if [ $# -eq 0 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

func_start() {
	"./manage_my_process" &
	pid=$$
	echo "$pid" | sudo tee /var/run/$file_name > /dev/null
	echo "manage_my_process started"
}

func_stop() {

	pid=$(pgrep -f "manage_my_process")
	kill "$pid"

	sudo rm -f "/var/run/$file_name"
	echo "manage_my_process stopped"
}

func_restart() {
	if [ -f "/var/run/$file_name" ]; then
		func_stop
	fi

	func_start

	echo "manage_my_process restarted"
}

case "$1" in
	start)
		func_start
		;;
	stop)
		func_stop
		;;
	restart)
		func_restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
