#!/usr/bin/env bash
# a bash (init) script that manages a file with start, stop and restart cmd
file_name="my_process.pid"

if [ "$#" == 0 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

if [[ "$#" == "1" ]]; then
	if [[ "$1" == "start" ]]; then
		./manage_my_process &
		pid=$!
		echo "$pid" > /var/run/$file_name
		echo "manage_my_process started"

	elif [[ "$1" == "stop" ]]; then
		if test -f "/var/run/$file_name"; then
			pid=$(cat /var/run/$file_name)
			kill -s SIGSTOP $pid
		fi
		sudo rm -f "/var/run/$file_name"
		echo "manage_my_process stopped"

	elif [[ "$1" == "restart" ]]; then
		if test -f "/var/run/$file_name"; then
			pid=$(cat /var/run/$file_name)
			kill -s SIGSTOP $pid
		fi
		./manage_my_process &
		pid=$!
		echo "$pid" > /var/run/$file_name
		echo "manage_my_process restarted"
	fi
fi
