#!/usr/bin/env bash
# a Bash script that displays a message with a sleep 2 in between
handle_sigterm() {
	echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
