#!/usr/bin/env bash
# a Bash script that kills the process 7-highlander
file_name="7-highlander"
pid=$(pgrep -f "$file_name")
if [ -z "$pid" ];then
	echo "No process for: $file_name"
else
	kill -9 "$pid"
fi
