#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd
# displays: username, user id, home directory path for the user

file_path="/etc/passwd"

while IFS=: read -r username _ userid _ _ home_directory _; do
	echo "$username:$userid:$home_directory"
done < $file_path
