#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
count=1
while [ $count -le 20 ]; do
	if [ $count == 5 ]; then
		echo "bad luck from China"
		echo $count
	elif [ $count == 10 ]; then
		echo "bad luck from Japan"
		echo $count
	elif [ $count == 18 ]; then
		echo "bad luck from Italy"
		echo $count
	else
		echo $count
	fi
	((count++))
done
