#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
count=1
num_18=18
num_5=5
num_10=10
while [ $count -le 20 ]; do

	case "$num_18" in
		$count)
			echo "bad luck from Italy";;
	esac

	case "$num_5" in
		$count)
			echo "bad luck from China";;
	esac

	case "$num_10" in
		$count)
			echo "bad luck from Japan";;
	esac

	echo $count
	((count++))

done
