#!/usr/bin/env bash
# a Bash script that gives you information about the school file
# Your Bash script should check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

func_file_information() {
	file_name="school"
	existing=false
	empty=true
	regular=false

	for files in *; do
		if [[ $files == "$file_name" && -d "$file_name" ]]; then
			regular=false
			existing=true
			empty=false
		fi
		if [[ $files == "$file_name" && -f "$file_name" ]]; then
			existing=true
			regular=true
			if [[ $(wc -c < "$file_name") -gt 0 ]]; then
				empty=false
			fi
		fi

	done

	if [[ $existing == true ]]; then
		echo "$file_name file exists"
		if [[ $empty == false ]]; then
			echo "$file_name file is not empty"

		else
			echo "$file_name file is empty"
		fi

	else
		echo "$file_name file does not exist"
	fi

	if [[ $regular == true ]]; then
		echo "$file_name is a regular file"
	fi
}

func_file_information
