#!/usr/bin/env bash
# a bash script thay resolves a host to an ip

touch ~/hosts.backup
sudo cp /etc/hosts ~/hosts.backup
sudo sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts
