#!/usr/bin/env bash
# a bash script runs nginx as nginx user

nginx_conf="/etc/nginx/nginx.conf"

# create nginx user
nginx_user=$(grep -E "^user\s+nginx;" "$nginx_conf" | awk '{print $2}' | tr -d ';')
if [ "$nginx_user" != "nginx" ]; then
	sed -i 's/^user .*/user nginx;/' "$nginx_conf"
fi

# set port 8080 listening port if not listening to port 8080
if ! grep -E "^listen\s+\*:8080;" "$nginx_conf" &>/dev/null; then
	sed -i '/^listen .*/ a \    listen *:8080;' "$nginx_conf"
fi
sudo -u nginx systemctl restart nginx
